### ISSUE TITLE
Automatic Updates, KODI18, ValdikSS

### ISSUE THREAD

**Issue by siliconhippy** [SCP002/m3u-gen-aceproxy#1]
Great idea !

Just noticed after looking at ValdikSS Aceproxy that AlexElec.in.ua is using...

1. Can this be applied to Aceproxy besides httpAceProxy ?

2. Is there a Kodi18 plugin/config available?

3. If I want automatic updates, can I just run ./src/m3u_gen_aceproxy.py under crontab daily ( for AlexElec Kodi JeOS) along with Acestream/Noxbit for the other packages ( Acestream/Noxbit)?

This might save some CPU/memory resources as opposed to always running in background?

4. Does running m3u format require upload bandwidth as in Acestream/torrents themselves? 

5. I am thinking I can use the Acestream CIDs with your package in KODI IPTV Simple Client PVR. Can this be done alongwith  IPTV links from other sources?

Cheers,
😁
Shippy.

**Comment by SCP002** [comment]
**RUS**:
---
Привет.
Приношу извинения за поздний ответ, не включены оповещения, новый 'ишью' заметил случайно.

1. Если под Aceproxy имеется ввиду [форк от ValdikSS](https://github.com/ValdikSS/aceproxy), то не пробовал, но если запущенное aceproxy отвечает на 'http://127.0.0.1:8000/channels' ([смотри конфиг](https://github.com/SCP002/m3u-gen-aceproxy/blob/master/src/config/config.py#L121)) XML файлом с каналами, то вполне может быть.

2. О коди знаю мало. Ничего специального под него не делал.
Так как там плагины писаны на питоне, то можно в теории эту штуку туда прилепить.

3. Не уверен в специфике работы crontab, но без модификаций кода с ним, чувствую, будут проблемы.
Этот генератор работает по следующему принципу:
Он запускает консольный процесс, бесконечно повторяющий создание плейлистов с заданным интервалом времени.
Crontab будет плодить вечно живущие консольные сессии (так ли это?).
Если нужно через crontab, то добавь **перед** [этой](https://github.com/SCP002/m3u-gen-aceproxy/blob/master/src/m3u_gen_aceproxy.py#L44) строчкой, с тем-же отступом, какое-нибудь 'exit(0)'.
А вообще, задумывался весь процесс так: Запустил генератор где-то на сервере у себя, свернул консоль, забыл о ней.

4. Ресурсов (любых) программа потребляет очень мало.
Работая на заднем фоне, она не делает ничего 99% времени.
Касательно сети: Всё, что этот генератор в частности делает, это обращается к AceProxy за XML файлом с каналами и парсит его. Сам AceProxy их берёт, по-моему, с torrent-tv.ru, что есть считанные килобайты (так ли это?).

5. Для обычного AceStream, **не AceProxy**, есть такой-же [генератор](https://github.com/SCP002/m3u-gen-acestream), специально под задачу.
Так-же есть [генератор для Noxbit](https://github.com/SCP002/m3u-gen-noxbit).
Ключевые отличия от этой программы: В отличии от этого, другие генераторы берут данные о каналах их так называемой '[помойки](http://91.92.66.82/trash/ttv-list/)'.

Надеюсь на все вопросы ответил приемлемо 😄.

-----

**ENG**:
---
Hello.
I apologize for the late reply, notification alerts was disabled, just noticed new issue by chance.

1. If Aceproxy means [fork from ValdikSS](https://github.com/ValdikSS/aceproxy), then I did not tried, but if the running aceproxy responds to 'http://127.0.0.1:8000/channels' ([see config](https://github.com/SCP002/m3u-gen-aceproxy/blob/master/src/config/config.py#L121)) with an XML file with channels, then probably could work.

2. I do not know too much about KODI. I didn't do anything special for that platform.
But since plug-ins are written with python, you can try to adapt this program to it.

3. I'm not sure about the specifics of crontab, but I feel there will be problems without modifications to the code.
This generator works on the following principle:
It starts the console process, endlessly repeating the creation of playlists with a specified time interval.
Crontab will produce ever-living console sessions (is this true?).
If you need use crontab, then add **before** [this](https://github.com/SCP002/m3u-gen-aceproxy/blob/master/src/m3u_gen_aceproxy.py#L44) line, with the same indent, something like 'exit (0)'.
In general, the whole process was conceived like this: You start the generator somewhere on your server, minimize the console window, forgot about it.

4. This program consumes very little resources.
Working in the background, it does nothing 99% of the time.
About the network: All that this generator in particular does is access to AceProxy for an XML file with channels and parse it. AceProxy itself takes channels, if I remember correctly, from torrent-tv.ru, which is only a few kilobytes in size (is this true?).

5. For a regular AceStream, **not AceProxy**, there is the same [generator](https://github.com/SCP002/m3u-gen-acestream), specifically for the task.
There is also a [generator for Noxbit](https://github.com/SCP002/m3u-gen-noxbit).
Key differences from this program: Unlike this, other generators take data on the channels of their so-called '[pomoyka](http://91.92.66.82/trash/ttv-list/)'.

Hope all the questions was answered acceptably 😄.
